### ISSUE TITLE
Please deprecate

### ISSUE THREAD

**Issue by nolanlawson** [calvinmetcalf/pouchdb-promise#1]
Based on discussion in https://github.com/pouchdb/pouchdb/pull/3730, we're going to expose an "extras" API. So people should be able to just do `require('pouchdb/extras/promise')` instead.

**Comment by calvinmetcalf** [comment]
What if you want to use this outside of pouchdb?

**Comment by nolanlawson** [comment]
Right, then you need a dependency on pouchdb, and you `require('pouchdb/extras/promise')`. Yes unfortunately it will `npm install` all of pouchdb, but then when you browserify you only get the promise code, which looks like this: https://github.com/pouchdb/pouchdb/blob/a7a46aca887574da4c32c24e7bb633f55eceb795/lib/deps/promise.js

**Comment by calvinmetcalf** [comment]
yeah I'd really prefer not to have pouchdb be a direct dependency of things like crypto-pouch when all I need is the promises

**Comment by nolanlawson** [comment]
This is a small enough lib that I can see where you're coming from. :) But I'm kinda surprised; I thought you'd consider my `require('pouchdb/extras/promise')` trick to be a nice solution.

crypto-pouch already has a devDependency on pouchdb; what's the problem with making it a regular dependency...? Or is there another reason to avoid `require('pouchdb/extras/*')` that I'm not aware of?

**Comment by calvinmetcalf** [comment]
if somebody using crypto-pouch and had a conflicting version range compared
with crypto-pouch pouchdb would be depended on twice, it also means that
anyone who happened to use this for a non pouchdb related purpose (I might
have I don't really remember) then they'd get pouchdb for no reason.

**Comment by nolanlawson** [comment]
ah okay, makes sense

**Comment by nolanlawson** [comment]
Actually now this will be a core part of the PouchDB monorepo, so I'll close this.

**Comment by nolanlawson** [comment]
Although probably this repo itself ought to be deprecated, since we'll publish from the PouchDB master repo instead.
